In [1]:
#import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter
import seaborn as sns
import iso3166

In [2]:

#read in the csv
data = pd.read_csv("Airplane_Crashes_and_Fatalities_Since_1908.csv")
data.head(10)

,Date,Time,Location,Operator,Flight #,Route,Type,Registration,cn/In,Aboard,Fatalities,Ground,Summary
0,09/17/1908,17:18,"Fort Myer, Virginia",Military - U.S. Army,NaN,Demonstration,Wright Flyer III,NaN,1,2.0,1.0,0.0,"During a demonstration flight, a U.S. Army fly..."
1,07/12/1912,06:30,"AtlantiCity, New Jersey",Military - U.S. Navy,NaN,Test flight,Dirigible,NaN,NaN,5.0,5.0,0.0,First U.S. dirigible Akron exploded just offsh...
2,08/06/1913,NaN,"Victoria, British Columbia, Canada",Private,-,NaN,Curtiss seaplane,NaN,NaN,1.0,1.0,0.0,The first fatal airplane accident in Canada oc...
3,09/09/1913,18:30,Over the North Sea,Military - German Navy,NaN,NaN,Zeppelin L-1 (airship),NaN,NaN,20.0,14.0,0.0,The airship flew into a thunderstorm and encou...
4,10/17/1913,10:30,"Near Johannisthal, Germany",Military - German Navy,NaN,NaN,Zeppelin L-2 (airship),NaN,NaN,30.0,30.0,0.0,Hydrogen gas which was being vented was sucked...
5,03/05/1915,01:00,"Tienen, Belgium",Military - German Navy,NaN,NaN,Zeppelin L-8 (airship),NaN,NaN,41.0,21.0,0.0,Crashed into trees while attempting to land af...
6,09/03/1915,15:20,"Off Cuxhaven, Germany",Military - German Navy,NaN,NaN,Zeppelin L-10 (airship),NaN,NaN,19.0,19.0,0.0,"Exploded and burned near Neuwerk Island, when..."
7,07/28/1916,NaN,"Near Jambol, Bulgeria",Military - German Army,NaN,NaN,Schutte-Lanz S-L-10 (airship),NaN,NaN,20.0,20.0,0.0,"Crashed near the Black Sea, cause unknown."
8,09/24/1916,01:00,"Billericay, England",Military - German Navy,NaN,NaN,Zeppelin L-32 (airship),NaN,NaN,22.0,22.0,0.0,Shot down by British aircraft crashing in flames.
9,10/01/1916,23:45,"Potters Bar, England",Military - German Navy,NaN,NaN,Zeppelin L-31 (airship),NaN,NaN,19.0,19.0,0.0,Shot down in flames by the British 39th Home D...

In [3]:
data.shape

(5268, 13)

In [4]:
data.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5268 entries, 0 to 5267
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          5268 non-null   object
 1   Time          3049 non-null   object
 2   Location      5248 non-null   object
 3   Operator      5250 non-null   object
 4   Flight #      1069 non-null   object
 5   Route         3562 non-null   object
 6   Type          5241 non-null   object
 7   Registration  4933 non-null   object
 8   cn/In         4040 non-null   object
 9   Aboard        5246 non-null   float64
 10  Fatalities    5256 non-null   float64
 11  Ground        5246 non-null   float64
 12  Summary       4878 non-null   object
dtypes: float64(3), object(10)
memory usage: 535.2+ KB

In [5]:
data.describe().T

             count       mean        std  min  25%   50%   75%     max
Aboard      5246.0  27.554518  43.076711  0.0  5.0  13.0  30.0   644.0
Fatalities  5256.0  20.068303  33.199952  0.0  3.0   9.0  23.0   583.0
Ground      5246.0   1.608845  53.987827  0.0  0.0   0.0   0.0  2750.0

In [6]:
data['Date'].value_counts()

08/27/1992    4
08/28/1976    4
09/11/2001    4
02/28/1973    4
06/18/1972    4
             ..
12/18/2003    1
01/10/1991    1
09/14/2002    1
01/08/1959    1
03/09/2000    1
Name: Date, Length: 4753, dtype: int64

In [7]:
data['Time'].value_counts()

15:00    32
12:00    31
11:00    29
16:00    26
19:30    26
         ..
00:35     1
06:22     1
05:50     1
21:46     1
21:48     1
Name: Time, Length: 1005, dtype: int64

In [8]:
data['Location'].value_counts()

Moscow, Russia                     15
Sao Paulo, Brazil                  15
Rio de Janeiro, Brazil             14
Anchorage, Alaska                  13
Manila, Philippines                13
                                   ..
Islip, New York                     1
Mt. Elk, Wyoming                    1
Near Puerto Inca, Huanuco, Peru     1
Near Newhall, California            1
Off Namibia, Africa                 1
Name: Location, Length: 4303, dtype: int64

In [9]:
data['Operator'].value_counts()

Aeroflot                                         179
Military - U.S. Air Force                        176
Air France                                        70
Deutsche Lufthansa                                65
Air Taxi                                          44
                                                ...
Northwest Airlines                                 1
Air Jordan                                         1
Avia-Taxi                                          1
Air Taxi - Flying School of the Cascades Inc.      1
Mustique Airways                                   1
Name: Operator, Length: 2476, dtype: int64

In [10]:
data['Flight #'].value_counts()

-       67
1       10
4        7
6        6
21       6
        ..
292      1
1996     1
5966     1
810      1
785      1
Name: Flight #, Length: 724, dtype: int64

In [11]:
data['Route'].value_counts()

Training                         81
Sightseeing                      29
Test flight                      17
Test                              6
Sao Paulo - Rio de Janeiro        5
                                 ..
Prague - Brun -  Pressburg        1
Rio de Janeiro - Buenos Aires     1
Tegucigalpa - Duzuna              1
Los Angeles, CA - Burbank, CA     1
Libya - England                   1
Name: Route, Length: 3244, dtype: int64

In [12]:
data['Type'].value_counts()

Douglas DC-3                                334
de Havilland Canada DHC-6 Twin Otter 300     81
Douglas C-47A                                74
Douglas C-47                                 62
Douglas DC-4                                 40
                                           ...
Douglas DC-3 (C-50A-DO)                       1
Convair CV-240-53                             1
Consolidated C-87                             1
Swearingen SA227-AC                           1
Fairchild-Hiller FH227C                       1
Name: Type, Length: 2446, dtype: int64

In [13]:
data['Registration'].value_counts()

49            3
CCCP-09303    2
N864JA        2
412           2
N91303        2
             ..
JY-ACB        1
44-70286      1
N401RA        1
VH-SWP        1
N215AA        1
Name: Registration, Length: 4905, dtype: int64

In [14]:
data['cn/In'].value_counts()

178          6
229          5
213          5
125          5
19           5
            ..
22554        1
CC-827B /    1
790323       1
26683        1
203          1
Name: cn/In, Length: 3707, dtype: int64

In [15]:
#counting missing value percentage for each column
percent_missing = data.isna().sum()/ len(data) *100
missing_value_df = pd.DataFrame({'percent_missing': percent_missing})
missing_value_df.sort_values(by=['percent_missing'], ascending=False)

              percent_missing
Flight #            79.707669
Time                42.122248
Route               32.384207
cn/In               23.310554
Summary              7.403189
Registration         6.359150
Type                 0.512528
Aboard               0.417616
Ground               0.417616
Location             0.379651
Operator             0.341686
Fatalities           0.227790
Date                 0.000000

Dropping Flight #, Time, Route, and CN/Ln, because of their missing values.
Also dropping registration and summary because they are useless data.

In [16]:
crashes = data[['Date', 'Location', 'Operator','Type', 'Aboard', 'Fatalities', 'Ground']]
crashes

,Date,Location,Operator,Type,Aboard,Fatalities,Ground
0,09/17/1908,"Fort Myer, Virginia",Military - U.S. Army,Wright Flyer III,2.0,1.0,0.0
1,07/12/1912,"AtlantiCity, New Jersey",Military - U.S. Navy,Dirigible,5.0,5.0,0.0
2,08/06/1913,"Victoria, British Columbia, Canada",Private,Curtiss seaplane,1.0,1.0,0.0
3,09/09/1913,Over the North Sea,Military - German Navy,Zeppelin L-1 (airship),20.0,14.0,0.0
4,10/17/1913,"Near Johannisthal, Germany",Military - German Navy,Zeppelin L-2 (airship),30.0,30.0,0.0
...,...,...,...,...,...,...,...
5263,05/20/2009,"Near Madiun, Indonesia",Military - Indonesian Air Force,Lockheed C-130 Hercules,112.0,98.0,2.0
5264,05/26/2009,"Near Isiro, DemocratiRepubliCongo",Service Air,Antonov An-26,4.0,4.0,NaN
5265,06/01/2009,"AtlantiOcean, 570 miles northeast of Natal, Br...",Air France,Airbus A330-203,228.0,228.0,0.0
5266,06/07/2009,"Near Port Hope Simpson, Newfoundland, Canada",Strait Air,Britten-Norman BN-2A-27 Islander,1.0,1.0,0.0
5267,06/08/2009,"State of Arunachal Pradesh, India",Military - Indian Air Force,Antonov An-32,13.0,13.0,0.0

In [17]:
#making the location data column into a list of countries for tableau interpretation

In [18]:
countries = iso3166.countries_by_name

listOfCountries = []
for i in countries:
    i = i.lower()
    listOfCountries.append(i)
listOfCountries

['afghanistan',
 'åland islands',
 'albania',
 'algeria',
 'american samoa',
 'andorra',
 'angola',
 'anguilla',
 'antarctica',
 'antigua and barbuda',
 'argentina',
 'armenia',
 'aruba',
 'australia',
 'austria',
 'azerbaijan',
 'bahamas',
 'bahrain',
 'bangladesh',
 'barbados',
 'belarus',
 'belgium',
 'belize',
 'benin',
 'bermuda',
 'bhutan',
 'bolivia, plurinational state of',
 'bonaire, sint eustatius and saba',
 'bosnia and herzegovina',
 'botswana',
 'bouvet island',
 'brazil',
 'british indian ocean territory',
 'brunei darussalam',
 'bulgaria',
 'burkina faso',
 'burundi',
 'cambodia',
 'cameroon',
 'canada',
 'cabo verde',
 'cayman islands',
 'central african republic',
 'chad',
 'chile',
 'china',
 'christmas island',
 'cocos (keeling) islands',
 'colombia',
 'comoros',
 'congo',
 'congo, democratic republic of the',
 'cook islands',
 'costa rica',
 "côte d'ivoire",
 'croatia',
 'cuba',
 'curaçao',
 'cyprus',
 'czechia',
 'denmark',
 'djibouti',
 'dominica',
 'dominican republic',
 'ecuador',
 'egypt',
 'el salvador',
 'equatorial guinea',
 'eritrea',
 'estonia',
 'ethiopia',
 'falkland islands (malvinas)',
 'faroe islands',
 'fiji',
 'finland',
 'france',
 'french guiana',
 'french polynesia',
 'french southern territories',
 'gabon',
 'gambia',
 'georgia',
 'germany',
 'ghana',
 'gibraltar',
 'greece',
 'greenland',
 'grenada',
 'guadeloupe',
 'guam',
 'guatemala',
 'guernsey',
 'guinea',
 'guinea-bissau',
 'guyana',
 'haiti',
 'heard island and mcdonald islands',
 'holy see',
 'honduras',
 'hong kong',
 'hungary',
 'iceland',
 'india',
 'indonesia',
 'iran, islamic republic of',
 'iraq',
 'ireland',
 'isle of man',
 'israel',
 'italy',
 'jamaica',
 'japan',
 'jersey',
 'jordan',
 'kazakhstan',
 'kenya',
 'kiribati',
 "korea, democratic people's republic of",
 'korea, republic of',
 'kosovo',
 'kuwait',
 'kyrgyzstan',
 "lao people's democratic republic",
 'latvia',
 'lebanon',
 'lesotho',
 'liberia',
 'libya',
 'liechtenstein',
 'lithuania',
 'luxembourg',
 'macao',
 'north macedonia',
 'madagascar',
 'malawi',
 'malaysia',
 'maldives',
 'mali',
 'malta',
 'marshall islands',
 'martinique',
 'mauritania',
 'mauritius',
 'mayotte',
 'mexico',
 'micronesia, federated states of',
 'moldova, republic of',
 'monaco',
 'mongolia',
 'montenegro',
 'montserrat',
 'morocco',
 'mozambique',
 'myanmar',
 'namibia',
 'nauru',
 'nepal',
 'netherlands',
 'new caledonia',
 'new zealand',
 'nicaragua',
 'niger',
 'nigeria',
 'niue',
 'norfolk island',
 'northern mariana islands',
 'norway',
 'oman',
 'pakistan',
 'palau',
 'palestine, state of',
 'panama',
 'papua new guinea',
 'paraguay',
 'peru',
 'philippines',
 'pitcairn',
 'poland',
 'portugal',
 'puerto rico',
 'qatar',
 'réunion',
 'romania',
 'russian federation',
 'rwanda',
 'saint barthélemy',
 'saint helena, ascension and tristan da cunha',
 'saint kitts and nevis',
 'saint lucia',
 'saint martin (french part)',
 'saint pierre and miquelon',
 'saint vincent and the grenadines',
 'samoa',
 'san marino',
 'sao tome and principe',
 'saudi arabia',
 'senegal',
 'serbia',
 'seychelles',
 'sierra leone',
 'singapore',
 'sint maarten (dutch part)',
 'slovakia',
 'slovenia',
 'solomon islands',
 'somalia',
 'south africa',
 'south georgia and the south sandwich islands',
 'south sudan',
 'spain',
 'sri lanka',
 'sudan',
 'suriname',
 'svalbard and jan mayen',
 'eswatini',
 'sweden',
 'switzerland',
 'syrian arab republic',
 'taiwan, province of china',
 'tajikistan',
 'tanzania, united republic of',
 'thailand',
 'timor-leste',
 'togo',
 'tokelau',
 'tonga',
 'trinidad and tobago',
 'tunisia',
 'turkey',
 'turkmenistan',
 'turks and caicos islands',
 'tuvalu',
 'uganda',
 'ukraine',
 'united arab emirates',
 'united kingdom of great britain and northern ireland',
 'united states of america',
 'united states minor outlying islands',
 'uruguay',
 'uzbekistan',
 'vanuatu',
 'venezuela, bolivarian republic of',
 'viet nam',
 'virgin islands, british',
 'virgin islands, u.s.',
 'wallis and futuna',
 'western sahara',
 'yemen',
 'zambia',
 'zimbabwe']

In [19]:
dataLocations = crashes['Location'].fillna("no data")
#dataLocations

In [20]:
locs = []
for loc in dataLocations:
    locs.append(loc.lower())
locs

['fort myer, virginia',
 'atlanticity, new jersey',
 'victoria, british columbia, canada',
 'over the north sea',
 'near johannisthal, germany',
 'tienen, belgium',
 'off cuxhaven, germany',
 'near jambol, bulgeria',
 'billericay, england',
 'potters bar, england',
 'mainz, germany',
 'off west hartlepool, england',
 'near gent, belgium',
 'off northern germany',
 'near texel island, north sea',
 'off vlieland island, north sea',
 'off western denmark',
 'near luneville, france',
 'over the mediterranean',
 'off helgoland island, germany',
 'ameland island, north sea',
 'elizabeth, new jersey',
 'cleveland, ohio',
 'dix run, pennsylvania',
 'newcastle, england',
 'cantonsville, maryland',
 'english channel',
 'long valley, new jersey',
 'new paris, indiana',
 'newark, new jersey',
 'newark, new jersey',
 'heller field, new jersey',
 'oskaloosa, iowa',
 'cleveland, ohio',
 'bedford, england',
 'college park, maryland',
 'morristown, new jersey',
 'pemberville, ohio',
 'hillersburg, pennsylvania',
 'off port vendres, france',
 'valencia, spain',
 'batavia, illinois',
 'tie siding, wyoming',
 'cricklewood, england',
 'barcelona, spain',
 'mendotta, minnisota',
 'la crosse, wisconsin',
 'off gibraltar',
 'elko, nevada',
 'point cook, australia',
 'mitchel field, ny',
 'cleveland, ohio',
 'rock springs, wyoming',
 'san francisco, california',
 'toulouse, france',
 'river humber, england',
 'paris, france',
 'near murchinson river, australia',
 'paris, france',
 'near norfolk, virginia',
 'grandvilliers, france',
 'pao ting fou, china',
 'brooklands, england',
 'nittany mt, ohio',
 'off folkestone, kent, england',
 'cadix, spain',
 'indianapolis, indiana',
 'venice, italy',
 'larache, morocco',
 'fez, morocco',
 'ajaccio, france',
 'barcelona, spain',
 'cheyenne, wyoming',
 'meadville, pennsylvania',
 'monsures, france',
 'bucharest, romania',
 'colton, ohio',
 'berks, england',
 'russia',
 'castalia, ohio',
 'over the mediterranean sea',
 'egbert, wy',
 'grampian, pennsylvania',
 'over the english channel',
 'barranquilla, colombia',
 'united states',
 'cabrerolles, france',
 'goshen, indiana',
 'purley, england',
 'near tiflies, georgia, ussr',
 'alicante, spain',
 'alicante, spain',
 'landrécies, france',
 'alicante, spain',
 'rosas, spain',
 'budapest, hungary',
 'caldwell, ohio',
 'toul, france',
 'off boulogne-sur-mer, france',
 'montpelier, ohio',
 'staaken, germany',
 'english channel',
 'rossaugpt, czechoslovakia',
 'wolvertem, belgium',
 'juist, germany',
 'hurst, kent, england',
 'new york, new york',
 'bueren, germany',
 'english channel',
 'cape bojador, morocco',
 'medford, oregon',
 'lille, france',
 'rabat, morocco',
 'tambo, qld, australia',
 'king hill, idaho',
 'goshen, indiana',
 'floh, germany',
 'algiers, algeria',
 'amoneburg, germany',
 'sevenoaks, england',
 'willington, connecticut',
 'hadley, new jersey',
 'saale, germany',
 'schleiz, germany',
 'thies, mauritania',
 'new brunswick, new jersey',
 'strasburg, france',
 'over the gulf of finland',
 'corunna, indiana',
 'almeria, spain',
 'abuerio, spain',
 'france',
 'near canajoharie, new york',
 'solis, uruguay',
 'tarragona, spain',
 'france',
 'almeria, spain',
 'marquette, nebraska',
 'rio de janeiro, brazil',
 'off cape griz nez, france',
 'federal, wyoming',
 'minuesa, spain',
 'no data',
 'dearborn, minnesota',
 'radevormwald, germany',
 'frankfurt, germany',
 'lebo, kansas',
 'over the gulf of finland',
 'purley, england',
 'waalhaven harbor, netherlands',
 'near port townsend, bc, canada',
 'toul, france',
 'adelaide hills, australia',
 'pocatello, idaho',
 'heroldbach, germany',
 'gerona, spain',
 'polk, pennsylvania',
 'valence, france',
 'off gibraltar',
 'edgerton, ohio',
 'bristolville, ohio',
 'edgerton, ohio',
 'spur, texas',
 'brazil',
 'rio de janeiro, brazil',
 'letzlingen, germany',
 'huron, ohio',
 'chattanooga, tennessee',
 'reims, france',
 'stafford springs, connecticut',
 'cove, oregon',
 'near corfu, greece',
 'morgantown, west virginia',
 'off morocco',
 'newark, new jersey',
 'near beaumont, california',
 'san diego, california',
 'hungary',
 'algiers',
 'santiago de cuba, cuba',
 'barcelona, spain',
 'off dungeness, england',
 'st. paul, minnesota',
 'lake constance, switzerland',
 'columbus, ohio',
 'clovis, new mexico',
 'perpignan, france',
 'sochi, russia',
 'elm, germany',
 'needles, california',
 'mt. taylor, new mexico',
 'jask, iran',
 'off larache, morocco',
 'jacumba, california',
 'mt lamentation, connecticut',
 'off spezia, italy',
 'mount vernon, ohio',
 'off bremerton, washington',
 'cerro del carbon, mexico',
 'near godstone, surrey, england',
 'off corsica, france',
 'vancouver, washington',
 'chagrin falls, ohio',
 'mediterranean sea',
 'near berlin, germany',
 'amarillo, texas',
 'brawnson, nebraska',
 'antananarivo, madagascar',
 'oceanside, california',
 'off ceuta, spain',
 'kansas city, kansas',
 'hartford, connecticut',
 'marden, england',
 'jersey city, new jersey',
 'buenos aires',
 'boston, massachusetts',
 'bornholm, denmark',
 'arkansas pass, texas',
 'iglau, czechoslovakia',
 'croydon, england',
 'southesk, saskatchewan, canada',
 'near beauvais, france',
 'dresden, germany',
 'la rache, morocco',
 'prince rupert, bc, canada',
 'near neufchatel, france',
 'brookston, indiana',
 'off of santos, brazil',
 'techachapi mountains, california',
 'shanghai, china',
 'melle, belgium',
 'bluff mountain, washington',
 'wairoa, new zealand',
 'bagot, manitoba, canada',
 'off spain',
 'new south wales, australia',
 'bazaar, kansas',
 'near letschen, germany',
 'burbank, california',
 'wampit, australia',
 'bellefonte, pennsylvania',
 'near sandoway, burma',
 'walbridge, ohio',
 'saarbrucken, germany',
 'chicago, illinois',
 'temora, australia',
 'centralia, illinois',
 'kurudjevo, bulgaria',
 'cincinnati, ohio',
 'chicago, illinois',
 'oakland, california',
 'novia scotia, canada',
 'brazil',
 'camden, new jersey',
 "sir lowry's pass, south africa",
 'salt lake city, utah',
 'near tsinan, china',
 'pasco, washington',
 'kewanee, illinois',
 'bangkok, thailand',
 'off algiers',
 'springfield, ohio',
 'colvin park, ilinois',
 'lebec, california',
 'off miami, florida',
 'marcellus, michigan',
 'rio vista, california',
 'off setiba, brazil',
 'saint louis, illinois',
 'calimesa, california',
 'steubenville, ohio',
 'syria',
 'bedford, ohio',
 'fort wayne, indiana',
 'portland, oregon',
 'burbank, california',
 'mount el plomo, near vitacura, chile',
 'beyrouth, lebanon',
 'tubergen, germany',
 'salt flats, texas',
 'selsdon park, england',
 'byron bay, australia',
 'port etienne, mauritania',
 'villa monte, bolivia',
 'ramsgate, england',
 'echterpfuhl, germany',
 'marianna, arkansas',
 'amarillo, texas',
 'rocky ridge, colorado',
 'wau, australia',
 'algiers',
 'newark, new jersey',
 'marietta, georgia',
 'bourne, texas',
 'eugene, oregon',
 'near mendoza, argentina',
 'hayward, california',
 'near dixmude, belgium',
 'hemkenrode, germany',
 'off barnegat, new jersey',
 'mt. terrione, italy',
 'traunstein, germany',
 'viladrau, spain',
 'bowling green, virginia',
 'quay, new mexico',
 'ljubljana, yugoslavia',
 'chesterton, indiana',
 'etobon, france',
 'portland, oregon',
 'moriarty, new mexico',
 'near tsinan, china',
 'near kharkov, ukraine, ussr',
 'wedron, illinois',
 'hamburg, germany',
 'eshowe, south africa',
 'near ruysselede, belgium',
 'corbigny, france',
 'carombe, france',
 'near salt lake city, utah',
 'rio de oro, morocco',
 'petersburg, illinois',
 'pereira, colombia',
 'near lima, peru',
 'ningpo bay, china',
 'english channel',
 'croydon, england',
 'mongaup mountain, new york',
 'junin, argentina',
 'chausseehausen, germany',
 'burbank, california',
 'san bernardino, california',
 'near tuttlingen, germany',
 'bahia, brazil',
 'ningbo, china',
 'amazonia, missouri',
 'near winton, australia',
 'bass strait, australia',
 'kiapit, australia',
 'near longreach, australia',
 'near longreach, nsw, australia',
 'amazonia, montana',
 'salchau, germany',
 'columbia, missouri',
 'palma soriano, cuba',
 'rutbah wells, syria',
 'sunbright, tennessee',
 'pittsburgh, pennsylvania',
 'stettin, germany',
 'schievelbein, germany',
 'el arish, egypt',
 'off samland, germany',
 'beauvais, france',
 'brilon, germany',
 'near walsenberg, colorado',
 'atlanta, missouri',
 'flint, michigan',
 'near moscow, russia',
 'glendo, wyoming',
 'maywood, illinois',
 'san barbra, honduras',
 'medellin, colombia',
 'amsterdam, netherlands',
 'off chandeleur island, mississippi',
 'pian giacomo, switzerland',
 'hangow, china',
 'near gilmer, texas',
 'near glendo, wyoming',
 'walakpa, near point barrow, alaska',
 'burbank, california',
 'off finders island, victoria, australia',
 'near cheyenne, wyoming',
 'gulf of finland',
 'troy, new york',
 'cheyenne, wyoming',
 'off nhambupe, brazil',
 'near juticalpa, honduras',
 'near fort worth, texas',
 'istres, france',
 'tours, france',
 'croydon, england',
 'breslau, germany',
 'off alexandria, egypt',
 'goodwin, arkansas',
 'near cordillera, boliva',
 'off ajaccio, corsica, france',
 'denton, texas',
 'south atlantiocean',
 'near tengya, china',
 'amemeca, mexico',
 'pavillon, new york',
 'uniontown, pennsylvania',
 'port of spain, trinidad',
 'near turin, italy',
 'switzerland',
 'senlis, france',
 'basel, switzerland',
 'mount waverley, australia',
 'malmo, sweden',
 'hannover, germany',
 'mt. lihesten, norway',
 'off channel islands, jersey',
 'mazamet, france',
 'mexico',
 'st. louis, missouri',
 'choco, colombia',
 'altenkirchen, germany',
 'mirabella, greece',
 'english channel',
 'walsenberg, colorado',
 'napierville, illinois',
 'mexico',
 'no data',
 'near tabarz, germany',
 'near moscow',
 'nurnberg, germany',
 'london, england',
 'near grenoble, france',
 'off dakar, french west africa',
 'croydon, england',
 'near salt lake city, utah',
 'kellogg, idaho',
 'near milford, pennsylvania',
 'near dallas, texas',
 'nanking, china',
 'newhall, california',
 'near newhall, california',
 'oran, algeria',
 'off san francisco, california',
 'mcpherson ranges, queensland, australia',
 'bathurst, gambia',
 'near ouroux, france',
 'clifton, pennsylvania',
 'wetnum, germany',
 'lakehurst, new jersey',
 'stuttgart, germany',
 'off lae, new guinea',
 'hal, belgium',
 'wadi halfa, sudan',
 'off cristobal, panama',
 'chilang point, bias bay, china',
 'daytona beach, florida',
 'san luis, argentina',
 'wau, australia',
 'corsavy, france',
 'phaleron bay, greece',
 'palembang, netherlands indies',
 'haydens peak, wyoming',
 'mannheim, germany',
 'ostende, belgium',
 'croydon, london',
 'brindisi harbor, italy',
 'saint sauveur, france',
 'kasperske hory, czechoslovakia',
 'frankfurt, germany',
 'bozeman, montana',
 'pago pago, u.s. samoa',
 'north pine, ontario, canada',
 'off san clemente island, california',
 'kandalaksha, russia',
 'marseille, france',
 'guadalupe, mexico',
 'pontoise, france',
 'near wawona, cailifornia',
 'datia, india',
 'somerton, australia',
 'near formia, italy',
 'balbuena, mexico',
 'mangere, new zealand',
 'near saugus, california',
 'sao paulo, brazil',
 'cleveland, ohio',
 'germany',
 'alberno canal, bc, canada',
 'tanganyika',
 'mount  mercedario, chile',
 'billings, montana',
 'off sardinia, italy',
 'stulpica, romania',
 'near bogota colombia',
 'kisumu, kenya',
 'pacifiocean between manila and guam',
 'shishijima, japan',
 'debrecen, hungary',
 'kiel, germany',
 'guanabara, brazil',
 'bucharest, romania',
 'montnago, italy',
 'wangmoon, china',
 'innisfail, australia',
 'off bathurst, gambia',
 'grisons, switzerland',
 'soest, germany',
 'mt. dandenong, australia',
 'somerset, england',
 'channel islands, jersey',
 'schiphol, amsterdam',
 'regina, saskatchewan, canada',
 'bathurst, gambia',
 'bagdad, iraq',
 'off point reyes, california',
 'off kubashima, japan',
 'amsterdam, netherlands',
 'darwin, australia',
 'paris, france',
 'miles city, montana',
 'rio de janeiro, brazil',
 'katherine, australia',
 'atlantiocean between n.y. and bermuda',
 'mediterranean sea',
 'haren, belgium',
 'manzanares, colombia',
 'near adler, washington',
 'hannover, germany',
 'atlantiocean',
 'oklahoma city, oklahoma',
 'near marrakech, morocco',
 'mocambique',
 'near marrakech, morocco',
 'guayaquil, ecuador',
 'vlissingen, the netherlands',
 'konstanz, switzerland',
 'barcelona, spain',
 'rio de janerio, brazil',
 'off copenhagen, denmark',
 'lahore, india',
 'hannover, germany',
 'north sea',
 'gosport, england',
 'south of gibraltar',
 'off malta-luqa',
 'mogador, morocco',
 'denpasar, indonesia',
 'gulf of oman',
 'near loch lomond, scotland',
 'el segundo, california',
 'off prangli island, gulf of finland, estonia',
 'near ouistreham, france',
 'gulf of tonkin',
 'near canberra, australia',
 'cluj, romania',
 'near lovettsville, virginia',
 'near changyi, china',
 'berlin, germany',
 'near centerville, utah',
 'brauna, germany',
 'rio de janeiro, brazil',
 'mediterranean sea',
 'chicago, illinois',
 'off south africa',
 'near nagy-varad, hungary',
 'near kian, china',
 'near robertson, missouri',
 'armstrong, on, canada',
 'atlanta, georgia',
 'trontheim, norway',
 'elands bay, south africa',
 'bucharest, romania',
 'sea of japan',
 'arran, scotland',
 'ayr, scotland',
 'near sao paulo, brazil',
 'bollemont, france',
 'campbeltown, argyll, scotland',
 'san juan, puerto rico',
 'no data',
 'near moorhead, minnesota',
 'st. thomas, ontario, canada',
 'miami, florida',
 'near las vegas, nevada',
 'manado, indonesia',
 'near samarinda, borneo',
 'kupang, timor',
 'near kupang, timor',
 'no data',
 'english channel, near plymouth, england',
 'off belmont, brisbane, australia',
 'indian ocean',
 'off broome, australia',
 'wyndham, australia',
 'north sea',
 'kunming, china',
 'pine creek, australia',
 'salt lake city, utah',
 'miles city, montana',
 'near premier, west virginia',
 'off broken head, australia',
 'llanfair, england',
 'algiers, algeria',
 'no data',
 'trinidad',
 'invergordon, england',
 'near dunbeath, scotland',
 'ameur el ain, algeria',
 'kunming, china',
 'near coamo, puerto rico',
 'botwood, newfoundland',
 'no data',
 'palm springs, california',
 'norway',
 'fairfield, utah',
 'wien, vienna',
 'river tagus, lisbon, portugal',
 'near paramarino, dutch guyana',
 'off the brazilian coast,  atlantiocean',
 'ukiah, california',
 'near chaparra, peru',
 'near gander, newfoundland',
 'seattle, washington',
 'lisbon, portugal',
 'luishui, china',
 'himalaya, china',
 'archerfield aerodrome, queensland, australia',
 'off port moresby, new guinea',
 'off the coast of france',
 'red springs, north carolina',
 'near mackay, old, australia',
 'khartoum, sudan',
 'khartoum, sudan',
 'gibraltar',
 'brandon head, ireland',
 'trammel, kentucky',
 'ploesti, romania',
 'off townsville, australia',
 'fort hertz, china',
 'rio de janeiro, brazil',
 'off galveston, texas',
 'near maxton, north carolina',
 'near calcutta, india',
 'near centerville, tennessee',
 'st. donat, quebec, canada',
 'hallo, sweden',
 'columbus, georgia',
 'poona, india',
 'kunming, china',
 'kunming, china',
 'port moresby, new guinea',
 'suifu, china',
 'canal creek, australia',
 'lakeside, utah',
 'belgrad, yugoslavia',
 'memphis, tennessee',
 'china',
 'eubeoa, greece',
 'new guinea',
 'near nome, alaska',
 'belgrad, yugoslavia',
 'frederikstad, norway',
 'montreal, canada',
 'between calcutta to dinjan, china',
 'off calcutta, india',
 'carentan, france',
 'flamanville, france',
 'barneville, france',
 'kunming, china',
 'kweilin, china',
 'porto alegre, brazil',
 'north atlantiocean',
 'port logan, scotland',
 'funafuti, gilbert islands, pacifiocean',
 'naper, nebraska',
 'off antilla, cuba',
 'blythburgh, england',
 'freckelton, england',
 'preswick, scotland',
 'sao paulo, brazil',
 'belgrad, yugoslavia',
 'near mossman, queensland, australia',
 'alaska',
 'rio doce, brazil',
 'near dijon, france',
 'texas',
 'near sadiya, india',
 'bosnia',
 'sydney, australia',
 'telemark, norway',
 'hungary',
 'birkenhead, england',
 'hanford, california',
 'seljord, norway',
 'lewes, england',
 'tegucigalpa, nicaragua',
 'kenya',
 'malmo, sweden',
 'dinjan, china',
 'van nuys, california',
 'atlantiocean',
 'english channel',
 'near dinjan, india',
 'port of spain, trinidad',
 'burbank, california',
 'china',
 'near kunming, china',
 'timor, indonesia',
 'redesdale, australia',
 'near montieri, italy',
 'nunters burgh, england',
 'off oakland, california',
 'lagoa santa, brazil',
 'casablanca, morocco',
 'marion, virginia',
 'coral sea, off australia',
 'kunming, china',
 'morgantown, west virginia',
 'near perth, australia',
 'no data',
 'sweetwater, texas',
 'munchen, germany',
 'north barrule, isle of man, england',
 'washington d.c.',
 'manus island, new guinea',
 'hindhead, england',
 'roye, france',
 'netherlands, new guinea',
 'off drewin, ivory coast',
 'china',
 'gealdton, australia',
 'swanage, england',
 'bangalore, india',
 'north atlantiocean',
 'near kisumu, kenya',
 'near florence, south carolina',
 'new york, new york',
 'near san luis potosi, mexico',
 'fort de france, martinique',
 'ixtaccihuati, mexico',
 'florence, south carolina',
 'near milne bay, new guinea',
 'near kansas, missouri',
 'puncak jaya, papua new guinea',
 'near chihkiang, china',
 'lakeland, florida',
 'elvetham, england',
 'rennes, france',
 'melsbroek, belgium',
 'near peking, china',
 'timor sea, atlantiocean',
 'between shanghi and canton, china',
 'near chiringa, india',
 'tarapoto, peru',
 'chihchiang, china',
 'herrenalb, germany',
 'near chuka, india',
 'off corpus christi, texas',
 'near boccadi, italy',
 'near picinisco, italy',
 'near castel, libya',
 'himalayas',
 'new britain island, new guinea',
 "white's farm, england",
 'near rochefort , france',
 'off the florida coast',
 'near billings, montana',
 'voksenkollen, norway',
 'bangui, french equatorial africa',
 'new york city, new york',
 'birmingham, alabama',
 'changchun, china',
 'marseilles, france',
 'cheshire, connecticut',
 'crowsnest pass, alberta, canada',
 'near le mans, france',
 'mt. elk, wyoming',
 'negros, philippines',
 'charlottetown, pe, canada',
 'live oak springs, california',
 'near prague, czechoslovakia',
 'off hobart, tasmania',
 'near nanking, china',
 'between chungking and shanghai, china',
 'hobart mills, california',
 'ceylon, cocos islands, indian ocean',
 'rabat, malta',
 'near shensi, china',
 'liberiad, nicaragua',
 'pindi-khut ,india',
 'munson, florida',
 'richmond, virginia',
 'oslo, norway',
 'off amalfi, italy',
 'near abeokuta, nigeria',
 'taboga island, panama',
 'off malaya',
 'pau, france',
 'holyoke, massachusetts',
 'reading, pennsylvania',
 'tsinan, china',
 'cuenca, ecuador',
 'goodland, kansas',
 'off the panama coast',
 'bassein, burma',
 'oslo, norway',
 'lakehurst, new jersey',
 'malta-luqa, malta',
 'rouen, france',
 'moline, illinois',
 'cairo, egypt',
 'holtug, denmark',
 'le bourget, france',
 'elko, nevada',
 'bathurst, gambia',
 'nome, alaska',
 'estevan, saskatchewan, canada',
 'brussels, belgium',
 'puesto araujo, colombia',
 'near gander, newfoundland',
 'near tripoli, libya',
 'lochi mountain, china',
 'near hong kong international airport',
 'rio doce, brazil',
 'stephenville, newfoundland',
 'off penang, malaya',
 'apeldoorn, the netherlands',
 'cheyenne, wyoming',
 'near sefrou, morocco',
 'laramie, wyoming',
 'near chitral, india',
 'gebel kalamoun, egypt',
 'st leger-la-montagne, france',
 'cleveland, ohio',
 'lebec, california',
 'near cofre de perote, mexico',
 'amsterdam, netherlands',
 'north pacifiocean',
 'san jose, costa rica',
 'el palomar, argentina',
 'meshed, iran',
 'toledo, washington',
 'near osaka, japan',
 'mt. banahaur, philippines',
 'caribbean, atlantiocean',
 'near rio de janeiro, brazil',
 'near san diego, california',
 'lunghwa, shanghai, china',
 'michigan city, indiana',
 'walshville, illinois',
 'near shannon, ireland',
 'sao paulo, brazil',

In [21]:
locs[7] = "bulgaria"
#locs

In [22]:
state_names = ["Alaska", "Alabama", "Arkansas", "American Samoa", "Arizona", "California", "Colorado", "Connecticut", "District ", "of Columbia", "Delaware", "Florida", "Georgia", "Guam", "Hawaii", "Iowa", "Idaho", "Illinois", "Indiana", "Kansas", "Kentucky", "Louisiana", "Massachusetts", "Maryland", "Maine", "Michigan", "Minnesota", "Missouri", "Mississippi", "Montana", "North Carolina", "North Dakota", "Nebraska", "New Hampshire", "New Jersey", "New Mexico", "Nevada", "New York", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Puerto Rico", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Virginia", "Virgin Islands", "Vermont", "Washington", "Wisconsin", "West Virginia", "Wyoming"]
for i in range(len(state_names)):
    state_names[i] = state_names[i].lower()
#state_names

In [23]:
index = 0
for i in locs:
    for j in state_names:
        if j in i:
            locs[index] = "united states"
            
    index = index +1
locs

['united states',
 'united states',
 'victoria, british columbia, canada',
 'over the north sea',
 'near johannisthal, germany',
 'tienen, belgium',
 'off cuxhaven, germany',
 'bulgaria',
 'billericay, england',
 'potters bar, england',
 'mainz, germany',
 'off west hartlepool, england',
 'near gent, belgium',
 'off northern germany',
 'near texel island, north sea',
 'off vlieland island, north sea',
 'off western denmark',
 'near luneville, france',
 'over the mediterranean',
 'off helgoland island, germany',
 'ameland island, north sea',
 'united states',
 'united states',
 'united states',
 'newcastle, england',
 'united states',
 'english channel',
 'united states',
 'united states',
 'united states',
 'united states',
 'united states',
 'united states',
 'united states',
 'bedford, england',
 'united states',
 'united states',
 'united states',
 'united states',
 'off port vendres, france',
 'valencia, spain',
 'united states',
 'united states',
 'cricklewood, england',
 'barcelona, spain',
 'mendotta, minnisota',
 'united states',
 'off gibraltar',
 'united states',
 'point cook, australia',
 'mitchel field, ny',
 'united states',
 'united states',
 'united states',
 'toulouse, france',
 'river humber, england',
 'paris, france',
 'near murchinson river, australia',
 'paris, france',
 'united states',
 'grandvilliers, france',
 'pao ting fou, china',
 'brooklands, england',
 'united states',
 'off folkestone, kent, england',
 'cadix, spain',
 'united states',
 'venice, italy',
 'larache, morocco',
 'fez, morocco',
 'ajaccio, france',
 'barcelona, spain',
 'united states',
 'united states',
 'monsures, france',
 'bucharest, romania',
 'united states',
 'berks, england',
 'russia',
 'united states',
 'over the mediterranean sea',
 'egbert, wy',
 'united states',
 'over the english channel',
 'barranquilla, colombia',
 'united states',
 'cabrerolles, france',
 'united states',
 'purley, england',
 'united states',
 'alicante, spain',
 'alicante, spain',
 'landrécies, france',
 'alicante, spain',
 'rosas, spain',
 'budapest, hungary',
 'united states',
 'toul, france',
 'off boulogne-sur-mer, france',
 'united states',
 'staaken, germany',
 'english channel',
 'rossaugpt, czechoslovakia',
 'wolvertem, belgium',
 'juist, germany',
 'hurst, kent, england',
 'united states',
 'bueren, germany',
 'english channel',
 'cape bojador, morocco',
 'united states',
 'lille, france',
 'rabat, morocco',
 'tambo, qld, australia',
 'united states',
 'united states',
 'floh, germany',
 'algiers, algeria',
 'amoneburg, germany',
 'sevenoaks, england',
 'united states',
 'united states',
 'saale, germany',
 'schleiz, germany',
 'thies, mauritania',
 'united states',
 'strasburg, france',
 'over the gulf of finland',
 'united states',
 'almeria, spain',
 'abuerio, spain',
 'france',
 'united states',
 'solis, uruguay',
 'tarragona, spain',
 'france',
 'almeria, spain',
 'united states',
 'rio de janeiro, brazil',
 'off cape griz nez, france',
 'united states',
 'minuesa, spain',
 'no data',
 'united states',
 'radevormwald, germany',
 'frankfurt, germany',
 'united states',
 'over the gulf of finland',
 'purley, england',
 'waalhaven harbor, netherlands',
 'near port townsend, bc, canada',
 'toul, france',
 'adelaide hills, australia',
 'united states',
 'heroldbach, germany',
 'gerona, spain',
 'united states',
 'valence, france',
 'off gibraltar',
 'united states',
 'united states',
 'united states',
 'united states',
 'brazil',
 'rio de janeiro, brazil',
 'letzlingen, germany',
 'united states',
 'united states',
 'reims, france',
 'united states',
 'united states',
 'near corfu, greece',
 'united states',
 'off morocco',
 'united states',
 'united states',
 'united states',
 'hungary',
 'algiers',
 'santiago de cuba, cuba',
 'barcelona, spain',
 'off dungeness, england',
 'united states',
 'lake constance, switzerland',
 'united states',
 'united states',
 'perpignan, france',
 'sochi, russia',
 'elm, germany',
 'united states',
 'united states',
 'jask, iran',
 'off larache, morocco',
 'united states',
 'united states',
 'off spezia, italy',
 'united states',
 'united states',
 'cerro del carbon, mexico',
 'near godstone, surrey, england',
 'off corsica, france',
 'united states',
 'united states',
 'mediterranean sea',
 'near berlin, germany',
 'united states',
 'united states',
 'antananarivo, madagascar',
 'united states',
 'off ceuta, spain',
 'united states',
 'united states',
 'marden, england',
 'united states',
 'buenos aires',
 'united states',
 'bornholm, denmark',
 'united states',
 'iglau, czechoslovakia',
 'croydon, england',
 'southesk, saskatchewan, canada',
 'near beauvais, france',
 'dresden, germany',
 'la rache, morocco',
 'prince rupert, bc, canada',
 'near neufchatel, france',
 'united states',
 'off of santos, brazil',
 'united states',
 'shanghai, china',
 'melle, belgium',
 'united states',
 'wairoa, new zealand',
 'bagot, manitoba, canada',
 'off spain',
 'new south wales, australia',
 'united states',
 'near letschen, germany',
 'united states',
 'wampit, australia',
 'united states',
 'near sandoway, burma',
 'united states',
 'saarbrucken, germany',
 'united states',
 'temora, australia',
 'united states',
 'kurudjevo, bulgaria',
 'united states',
 'united states',
 'united states',
 'novia scotia, canada',
 'brazil',
 'united states',
 "sir lowry's pass, south africa",
 'united states',
 'near tsinan, china',
 'united states',
 'united states',
 'bangkok, thailand',
 'off algiers',
 'united states',
 'colvin park, ilinois',
 'united states',
 'united states',
 'united states',
 'united states',
 'off setiba, brazil',
 'united states',
 'united states',
 'united states',
 'syria',
 'united states',
 'united states',
 'united states',
 'united states',
 'mount el plomo, near vitacura, chile',
 'beyrouth, lebanon',
 'tubergen, germany',
 'united states',
 'selsdon park, england',
 'byron bay, australia',
 'port etienne, mauritania',
 'villa monte, bolivia',
 'ramsgate, england',
 'echterpfuhl, germany',
 'united states',
 'united states',
 'united states',
 'wau, australia',
 'algiers',
 'united states',
 'united states',
 'united states',
 'united states',
 'near mendoza, argentina',
 'united states',
 'near dixmude, belgium',
 'hemkenrode, germany',
 'united states',
 'mt. terrione, italy',
 'traunstein, germany',
 'viladrau, spain',
 'united states',
 'united states',
 'ljubljana, yugoslavia',
 'united states',
 'etobon, france',
 'united states',
 'united states',
 'near tsinan, china',
 'near kharkov, ukraine, ussr',
 'united states',
 'hamburg, germany',
 'eshowe, south africa',
 'near ruysselede, belgium',
 'corbigny, france',
 'carombe, france',
 'united states',
 'rio de oro, morocco',
 'united states',
 'pereira, colombia',
 'near lima, peru',
 'ningpo bay, china',
 'english channel',
 'croydon, england',
 'united states',
 'junin, argentina',
 'chausseehausen, germany',
 'united states',
 'united states',
 'near tuttlingen, germany',
 'bahia, brazil',
 'ningbo, china',
 'united states',
 'near winton, australia',
 'bass strait, australia',
 'kiapit, australia',
 'near longreach, australia',
 'near longreach, nsw, australia',
 'united states',
 'salchau, germany',
 'united states',
 'palma soriano, cuba',
 'rutbah wells, syria',
 'united states',
 'united states',
 'stettin, germany',
 'schievelbein, germany',
 'el arish, egypt',
 'off samland, germany',
 'beauvais, france',
 'brilon, germany',
 'united states',
 'united states',
 'united states',
 'near moscow, russia',
 'united states',
 'united states',
 'san barbra, honduras',
 'medellin, colombia',
 'amsterdam, netherlands',
 'united states',
 'pian giacomo, switzerland',
 'hangow, china',
 'united states',
 'united states',
 'united states',
 'united states',
 'off finders island, victoria, australia',
 'united states',
 'gulf of finland',
 'united states',
 'united states',
 'off nhambupe, brazil',
 'near juticalpa, honduras',
 'united states',
 'istres, france',
 'tours, france',
 'croydon, england',
 'breslau, germany',
 'off alexandria, egypt',
 'united states',
 'near cordillera, boliva',
 'off ajaccio, corsica, france',
 'united states',
 'south atlantiocean',
 'near tengya, china',
 'amemeca, mexico',
 'united states',
 'united states',
 'port of spain, trinidad',
 'near turin, italy',
 'switzerland',
 'senlis, france',
 'basel, switzerland',
 'mount waverley, australia',
 'malmo, sweden',
 'hannover, germany',
 'mt. lihesten, norway',
 'off channel islands, jersey',
 'mazamet, france',
 'mexico',
 'united states',
 'choco, colombia',
 'altenkirchen, germany',
 'mirabella, greece',
 'english channel',
 'united states',
 'united states',
 'mexico',
 'no data',
 'near tabarz, germany',
 'near moscow',
 'nurnberg, germany',
 'london, england',
 'near grenoble, france',
 'off dakar, french west africa',
 'croydon, england',
 'united states',
 'united states',
 'united states',
 'united states',
 'nanking, china',
 'united states',
 'united states',
 'oran, algeria',
 'united states',
 'mcpherson ranges, queensland, australia',
 'bathurst, gambia',
 'near ouroux, france',
 'united states',
 'wetnum, germany',
 'united states',
 'stuttgart, germany',
 'off lae, new guinea',
 'hal, belgium',
 'wadi halfa, sudan',
 'off cristobal, panama',
 'chilang point, bias bay, china',
 'united states',
 'san luis, argentina',
 'wau, australia',
 'corsavy, france',
 'phaleron bay, greece',
 'palembang, netherlands indies',
 'united states',
 'mannheim, germany',
 'ostende, belgium',
 'croydon, london',
 'brindisi harbor, italy',
 'saint sauveur, france',
 'kasperske hory, czechoslovakia',
 'frankfurt, germany',
 'united states',
 'pago pago, u.s. samoa',
 'north pine, ontario, canada',
 'united states',
 'kandalaksha, russia',
 'marseille, france',
 'guadalupe, mexico',
 'pontoise, france',
 'near wawona, cailifornia',
 'datia, india',
 'somerton, australia',
 'near formia, italy',
 'balbuena, mexico',
 'mangere, new zealand',
 'united states',
 'sao paulo, brazil',
 'united states',
 'germany',
 'alberno canal, bc, canada',
 'tanganyika',
 'mount  mercedario, chile',
 'united states',
 'off sardinia, italy',
 'stulpica, romania',
 'near bogota colombia',
 'kisumu, kenya',
 'united states',
 'shishijima, japan',
 'debrecen, hungary',
 'kiel, germany',
 'guanabara, brazil',
 'bucharest, romania',
 'montnago, italy',
 'wangmoon, china',
 'innisfail, australia',
 'off bathurst, gambia',
 'grisons, switzerland',
 'soest, germany',
 'mt. dandenong, australia',
 'somerset, england',
 'channel islands, jersey',
 'schiphol, amsterdam',
 'regina, saskatchewan, canada',
 'bathurst, gambia',
 'bagdad, iraq',
 'united states',
 'off kubashima, japan',
 'amsterdam, netherlands',
 'darwin, australia',
 'paris, france',
 'united states',
 'rio de janeiro, brazil',
 'katherine, australia',
 'atlantiocean between n.y. and bermuda',
 'mediterranean sea',
 'haren, belgium',
 'manzanares, colombia',
 'united states',
 'hannover, germany',
 'atlantiocean',
 'united states',
 'near marrakech, morocco',
 'mocambique',
 'near marrakech, morocco',
 'guayaquil, ecuador',
 'vlissingen, the netherlands',
 'konstanz, switzerland',
 'barcelona, spain',
 'rio de janerio, brazil',
 'off copenhagen, denmark',
 'lahore, india',
 'hannover, germany',
 'north sea',
 'gosport, england',
 'south of gibraltar',
 'off malta-luqa',
 'mogador, morocco',
 'denpasar, indonesia',
 'gulf of oman',
 'near loch lomond, scotland',
 'united states',
 'off prangli island, gulf of finland, estonia',
 'near ouistreham, france',
 'gulf of tonkin',
 'near canberra, australia',
 'cluj, romania',
 'united states',
 'near changyi, china',
 'berlin, germany',
 'united states',
 'brauna, germany',
 'rio de janeiro, brazil',
 'mediterranean sea',
 'united states',
 'off south africa',
 'near nagy-varad, hungary',
 'near kian, china',
 'united states',
 'armstrong, on, canada',
 'united states',
 'trontheim, norway',
 'elands bay, south africa',
 'bucharest, romania',
 'sea of japan',
 'arran, scotland',
 'ayr, scotland',
 'near sao paulo, brazil',
 'bollemont, france',
 'campbeltown, argyll, scotland',
 'united states',
 'no data',
 'united states',
 'st. thomas, ontario, canada',
 'united states',
 'united states',
 'manado, indonesia',
 'near samarinda, borneo',
 'kupang, timor',
 'near kupang, timor',
 'no data',
 'english channel, near plymouth, england',
 'off belmont, brisbane, australia',
 'indian ocean',
 'off broome, australia',
 'wyndham, australia',
 'north sea',
 'kunming, china',
 'pine creek, australia',
 'united states',
 'united states',
 'united states',
 'off broken head, australia',
 'llanfair, england',
 'algiers, algeria',
 'no data',
 'trinidad',
 'invergordon, england',
 'near dunbeath, scotland',
 'ameur el ain, algeria',
 'kunming, china',
 'united states',
 'botwood, newfoundland',
 'no data',
 'united states',
 'norway',
 'united states',
 'wien, vienna',
 'river tagus, lisbon, portugal',
 'near paramarino, dutch guyana',
 'off the brazilian coast,  atlantiocean',
 'united states',
 'near chaparra, peru',
 'near gander, newfoundland',
 'united states',
 'lisbon, portugal',
 'luishui, china',
 'himalaya, china',
 'archerfield aerodrome, queensland, australia',
 'off port moresby, new guinea',
 'off the coast of france',
 'united states',
 'near mackay, old, australia',
 'khartoum, sudan',
 'khartoum, sudan',
 'gibraltar',
 'brandon head, ireland',
 'united states',
 'ploesti, romania',
 'off townsville, australia',
 'fort hertz, china',
 'rio de janeiro, brazil',
 'united states',
 'united states',
 'near calcutta, india',
 'united states',
 'st. donat, quebec, canada',
 'hallo, sweden',
 'united states',
 'poona, india',
 'kunming, china',
 'kunming, china',
 'port moresby, new guinea',
 'suifu, china',
 'canal creek, australia',
 'united states',
 'belgrad, yugoslavia',
 'united states',
 'china',
 'eubeoa, greece',
 'new guinea',
 'united states',
 'belgrad, yugoslavia',
 'frederikstad, norway',
 'montreal, canada',
 'between calcutta to dinjan, china',
 'off calcutta, india',
 'carentan, france',
 'flamanville, france',
 'barneville, france',
 'kunming, china',
 'kweilin, china',
 'porto alegre, brazil',
 'north atlantiocean',
 'port logan, scotland',
 'funafuti, gilbert islands, pacifiocean',
 'united states',
 'off antilla, cuba',
 'blythburgh, england',
 'freckelton, england',
 'preswick, scotland',
 'sao paulo, brazil',
 'belgrad, yugoslavia',
 'near mossman, queensland, australia',
 'united states',
 'rio doce, brazil',
 'near dijon, france',
 'united states',
 'near sadiya, india',
 'bosnia',
 'sydney, australia',
 'telemark, norway',
 'hungary',
 'birkenhead, england',
 'united states',
 'seljord, norway',
 'lewes, england',
 'tegucigalpa, nicaragua',
 'kenya',
 'malmo, sweden',
 'dinjan, china',
 'united states',
 'atlantiocean',
 'english channel',
 'near dinjan, india',
 'port of spain, trinidad',
 'united states',
 'china',
 'near kunming, china',
 'timor, indonesia',
 'redesdale, australia',
 'near montieri, italy',
 'nunters burgh, england',
 'united states',
 'lagoa santa, brazil',
 'casablanca, morocco',
 'united states',
 'coral sea, off australia',
 'kunming, china',
 'united states',
 'near perth, australia',
 'no data',
 'united states',
 'munchen, germany',
 'north barrule, isle of man, england',
 'united states',
 'manus island, new guinea',
 'hindhead, england',
 'roye, france',
 'netherlands, new guinea',
 'off drewin, ivory coast',
 'china',
 'gealdton, australia',
 'swanage, england',
 'bangalore, india',
 'north atlantiocean',
 'near kisumu, kenya',
 'united states',
 'united states',
 'near san luis potosi, mexico',
 'fort de france, martinique',
 'ixtaccihuati, mexico',
 'united states',
 'near milne bay, new guinea',
 'united states',
 'puncak jaya, papua new guinea',
 'near chihkiang, china',
 'united states',
 'elvetham, england',
 'rennes, france',
 'melsbroek, belgium',
 'near peking, china',
 'timor sea, atlantiocean',
 'between shanghi and canton, china',
 'near chiringa, india',
 'tarapoto, peru',
 'chihchiang, china',
 'herrenalb, germany',
 'near chuka, india',
 'united states',
 'near boccadi, italy',
 'near picinisco, italy',
 'near castel, libya',
 'himalayas',
 'new britain island, new guinea',
 "white's farm, england",
 'near rochefort , france',
 'united states',
 'united states',
 'voksenkollen, norway',
 'bangui, french equatorial africa',
 'united states',
 'united states',
 'changchun, china',
 'marseilles, france',
 'united states',
 'crowsnest pass, alberta, canada',
 'near le mans, france',
 'united states',
 'negros, philippines',
 'charlottetown, pe, canada',
 'united states',
 'near prague, czechoslovakia',
 'off hobart, tasmania',
 'near nanking, china',
 'between chungking and shanghai, china',
 'united states',
 'ceylon, cocos islands, indian ocean',
 'rabat, malta',
 'near shensi, china',
 'liberiad, nicaragua',
 'pindi-khut ,india',
 'united states',
 'united states',
 'oslo, norway',
 'off amalfi, italy',
 'near abeokuta, nigeria',
 'taboga island, panama',
 'off malaya',
 'pau, france',
 'united states',
 'united states',
 'tsinan, china',
 'cuenca, ecuador',
 'united states',
 'off the panama coast',
 'bassein, burma',
 'oslo, norway',
 'united states',
 'malta-luqa, malta',
 'rouen, france',
 'united states',
 'cairo, egypt',
 'holtug, denmark',
 'le bourget, france',
 'united states',
 'bathurst, gambia',
 'united states',
 'estevan, saskatchewan, canada',
 'brussels, belgium',
 'puesto araujo, colombia',
 'near gander, newfoundland',
 'near tripoli, libya',
 'lochi mountain, china',
 'near hong kong international airport',
 'rio doce, brazil',
 'stephenville, newfoundland',
 'off penang, malaya',
 'apeldoorn, the netherlands',
 'united states',
 'near sefrou, morocco',
 'united states',
 'near chitral, india',
 'gebel kalamoun, egypt',
 'st leger-la-montagne, france',
 'united states',
 'united states',
 'near cofre de perote, mexico',
 'amsterdam, netherlands',
 'north pacifiocean',
 'san jose, costa rica',
 'el palomar, argentina',
 'meshed, iran',
 'united states',
 'near osaka, japan',
 'mt. banahaur, philippines',
 'caribbean, atlantiocean',
 'near rio de janeiro, brazil',
 'united states',
 'lunghwa, shanghai, china',
 'united states',
 'united states',
 'near shannon, ireland',
 'sao paulo, brazil',
 'united states',
 'tsingtao, china',
 'off laoag, china',
 'near lympne, england',
 'united states',
 'near puebla, mexico',
 'chongqing, china',
 'croydon, surrey, england',
 'hong kong',
 'copenhagen, denmark',
 'near hankow, china',
 'near lisbon, portugal',
 'united states',
 'pedro bernardo, spain',
 'united states',
 'off terracina, italy',
 'near bogota, colombia',
 'chungking, china',
 'china sea, pacifiocean',
 'cordillera, colombia',
 "l'isola di ischia, italy",
 'mt. moucherolles, france',
 'near medellin, colombia',
 'negombo, sri lanka',
 'near caracas, venezuela',
 'off dakar, senegal',
 'united states',
 'near cuzco, peru',
 'near vancouver, british columbia, canada',
 'united states',
 'hjedinsfjordur, iceland',
 'atsugi, japan',
 'united states',
 'united states',
 'near gemenos, france',
 'natal, argentina',
 'united states',
 'al mayadin, syria',
 'near eaeka, french cameroons',
 'united states',
 'vichy ,france',
 'az-zubair, iran',
 'moron, argentina',
 'near yumen, china',
 'andes, argentina',
 'north pacifiocean',
 'united states',
 'malmo, sweden',
 'bucharest, romania',
 'united states',
 'bahrain, persian gulf',
 'harsiad, norway',
 'united states',
 'united states',
 'off cartegena, spain',
 'united states',
 'united states',
 'near mt. hymettus, greece',
 'srinagar, india',
 'off barrio rizal, philippines',
 'united states',
 'near bouchox, france',
 'ravello, italy',
 'united states',
 'phouznicie, romania',
 'united states',
 'montenegrin mountains, yugoslavia',
 'no data',
 'near trappa, italy',
 'united states',
 'near goose bay, labrador',
 'united states',
 'kunming, china',

In [24]:
index = 0
for i in locs:
    for j in listOfCountries:
        if j in i:
            locs[index] = j
        elif "england" in i:
            locs[index] = "united kingdom"
            
    index = index +1

In [25]:
locationsFinal = []
for l in locs:
    locationsFinal.append(l.title())
    

crashes["Location"] = pd.DataFrame(locationsFinal)

<ipython-input-25-0493f53e50f5>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crashes["Location"] = pd.DataFrame(locationsFinal)

In [26]:
crashes["Location"]

0            United States
1            United States
2                   Canada
3       Over The North Sea
4                  Germany
               ...
5263             Indonesia
5264                 Congo
5265                Brazil
5266                Canada
5267                 India
Name: Location, Length: 5268, dtype: object

In [27]:
#convert the dataset's date column into the datetime datatype

pd.options.mode.chained_assignment = None 
crashes['Date'] = pd.to_datetime(crashes['Date'], format='%m/%d/%Y')
crashes

,Date,Location,Operator,Type,Aboard,Fatalities,Ground
0,1908-09-17,United States,Military - U.S. Army,Wright Flyer III,2.0,1.0,0.0
1,1912-07-12,United States,Military - U.S. Navy,Dirigible,5.0,5.0,0.0
2,1913-08-06,Canada,Private,Curtiss seaplane,1.0,1.0,0.0
3,1913-09-09,Over The North Sea,Military - German Navy,Zeppelin L-1 (airship),20.0,14.0,0.0
4,1913-10-17,Germany,Military - German Navy,Zeppelin L-2 (airship),30.0,30.0,0.0
...,...,...,...,...,...,...,...
5263,2009-05-20,Indonesia,Military - Indonesian Air Force,Lockheed C-130 Hercules,112.0,98.0,2.0
5264,2009-05-26,Congo,Service Air,Antonov An-26,4.0,4.0,NaN
5265,2009-06-01,Brazil,Air France,Airbus A330-203,228.0,228.0,0.0
5266,2009-06-07,Canada,Strait Air,Britten-Norman BN-2A-27 Islander,1.0,1.0,0.0
5267,2009-06-08,India,Military - Indian Air Force,Antonov An-32,13.0,13.0,0.0

In [28]:
#export to CSV
crashes.to_csv('crashesCleaned.csv', index=False)